deployment:
  image:
    repository: nginx
    tag: "1.25"
    pullPolicy: IfNotPresent
  openshiftOAuthProxy:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  containerSecurityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  automountServiceAccountToken: false
  readinessProbe:
    enabled: true
    httpGet:
      path: /
      port: 8080
  livenessProbe:
    enabled: true
    httpGet:
      path: /
      port: 8080

route:
  enabled: false

sealedSecret:
  enabled: false

externalSecret:
  enabled: false

grafanaDashboard:
  enabled: false

endpointMonitor:
  enabled: false

forecastle:
  enabled: false

serviceMonitor:
  enabled: false

alertmanagerConfig:
  enabled: false

prometheusRule:
  enabled: false

certificate:
  enabled: false

secretProviderClass:
  enabled: false

vpa:
  enabled: false

backup:
  enabled: false

httpRoute:
  enabled: false

extraObjects: []
