apiVersion: v2
name: application
description: Generic Helm chart for deploying stateless applications on Kubernetes
type: application
version: 9.0.0
keywords:
  - application
  - chart
  - stakater
  - helm
  - kubernetes
  - openshift
  - cronjob
  - deployment
  - ingress
  - monitoring
home: https://github.com/stakater/application
maintainers:
  - name: Stakater
    email: hello@stakater.com
icon: https://github.com/stakater/ForecastleIcons/blob/master/stakater.png
