apiVersion: v2
name: application
description: Generic helm chart for all kind of applications

type: application

# Helm chart Version

version: 2.2.16


keywords:
  - java
  - node
  - dotnet
  - kubernetes
  - stakater
  - application

home: https://github.com/stakater/application
maintainers:
- name: Stakater
  email: hello@stakater.com

icon: https://github.com/stakater/ForecastleIcons/blob/master/stakater.png
