{
 "title": "HAProxy Dashboard Example from chart",
 "tags": [ "haproxy" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(haproxy_server_http_responses_total, namespace)"
   },
   {
    "name": "route",
    "query": "label_values(haproxy_server_http_responses_total{namespace=~\"$namespace\"}, route)"
   },
   {
    "name": "code",
    "query": "label_values(haproxy_server_http_responses_total, code)"
   },
   { "name": "rate", "query": "1m,5m,30m,1h" },
   {
    "name": "router",
    "query": "label_values(haproxy_server_http_responses_total, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Failure Requests Rate (5xx)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_server_http_responses_total{code=\"5xx\", route=~\"$route\", namespace=~\"$namespace\", pod=~\"$router\"}[$rate])) by (namespace, code, route)",
     "legendFormat": "Route: {{route}}, Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Successful Requests Rate (2xx)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_server_http_responses_total{code=\"2xx\", route=~\"$route\", namespace=~\"$namespace\", pod=~\"$router\"}[$rate])) by (namespace, code, route)",
     "legendFormat": "Route: {{route}}, Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Number of requests by HTTP codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_server_http_responses_total{namespace=~\"$namespace\", route=~\"$route\", code=~\"$code\", pod=~\"$router\"}) by (namespace, route, code)",
     "legendFormat": "Code: {{code}}, Route: {{route}}, Namespace: {{namespace}}"
    }
   ]
  }
 ]
}