repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs-built
        args:
          # Keep args in sync with /.github/workflows/pull_request.yaml
          - --output-file=./../README.md
          - --template-files=./README.md.gotmpl
          - --sort-values-order=file
