[tools]
prek = "0.4.5"
helm = "4.2.1"
helm-docs = "1.14.2"
"github:dadav/helm-schema" = "0.23.4"
"ubi:helm-unittest/helm-unittest" = { version = "1.1.1", exe = "untt", rename_exe = "helm-unittest" }

[tasks.set-version]
description = "Bump the version of the Helm chart"
run = "./hack/set-version.sh"

[tasks.install-hooks]
description = "Install Git pre-commit hooks"
run = "prek install --install-hooks"

[tasks.gen-helm-docs]
alias = "gen-docs"
description = "Generate the Helm documentation"
run = """
# Keep args in sync with /.github/workflows/ci.yaml and /.pre-commit-config.yaml
helm-docs \\
  --output-file=./../README.md \\
  --template-files=./README.md.gotmpl \\
  --sort-values-order=file
"""

[tasks.gen-helm-schema]
alias = "gen-schema"
description = "Generate the Helm values schema"
run = """
helm-schema \\
  --chart-search-root application \\
  --helm-docs-compatibility-mode \\
  --append-newline \\
  --skip-auto-generation required \\
  --skip-auto-generation additionalProperties
"""

[tasks.generate]
alias = "gen"
description = "Generate all files"
depends = ["gen-docs", "gen-schema"]

[tasks.helm-lint]
description = "Lint the Helm chart"
run = "helm lint application"

[tasks.lint]
description = "Lint the Helm chart"
depends = ["helm-lint"]

[tasks.unit-test]
alias = "test"
description = "Run Helm unit tests"
run = "helm-unittest application"
