[tools]
prek = "0.4.0"
helm = "4.2.0"
helm-docs = "1.14.2"
"ubi:helm-unittest/helm-unittest" = { version = "1.1.0", exe = "untt", rename_exe = "helm-unittest" }

[tasks.set-version]
description = "Bump the version of the Helm chart"
run = "./hack/set-version.sh"

[tasks.install-hooks]
description = "Install Git pre-commit hooks"
run = "prek install --install-hooks"

[tasks.gen-helm-docs]
alias = "gen-docs"
description = "Generate the Helm documentation"
run = """
# Keep args in sync with /.github/workflows/ci.yaml and /.pre-commit-config.yaml
helm-docs \\
  --output-file=./../README.md \\
  --template-files=./README.md.gotmpl \\
  --sort-values-order=file
"""

[tasks.generate]
alias = "gen"
description = "Generate all files"
depends = ["gen-docs"]

[tasks.helm-lint]
description = "Lint the Helm chart"
run = "helm lint application"

[tasks.lint]
description = "Lint the Helm chart"
depends = ["helm-lint"]

[tasks.unit-test]
alias = "test"
description = "Run Helm unit tests"
run = "helm-unittest application"
