{{- if .Values.alertmanagerConfig -}}
{{- if .Values.alertmanagerConfig.enabled -}}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ template "application.namespace" . }}
  labels:
{{ include "application.labels.stakater" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{ toYaml .Values.alertmanagerConfig.selectionLabels | indent 4 }}
spec:
{{- if .Values.alertmanagerConfig.spec.route }}
    route:
{{ toYaml .Values.alertmanagerConfig.spec.route | indent 6 }}
{{- end -}}
{{- if .Values.alertmanagerConfig.spec.receivers }}
    receivers: 
{{ toYaml .Values.alertmanagerConfig.spec.receivers | indent 6 }}
{{- end -}}
{{- if .Values.alertmanagerConfig.spec.inhibitRules }}
    inhibitRules: {{ toYaml .Values.alertmanagerConfig.spec.inhibitRules | nindent 6 }}
{{- end -}}

{{- end -}}
{{- end -}}
