{{- if (.Values.backup).enabled }}
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: {{ printf "%s-backup" .Values.applicationName | trunc 63 | quote }}
  namespace: {{ .Values.backup.namespace | default ( include "application.namespace" . ) | quote }}
  labels:
  {{- include "application.labels" . | nindent 4 }}
spec:
  labelSelector:
    matchLabels:
       app.kubernetes.io/part-of: {{ include "application.name" . }}
  includedNamespaces:
    - {{ include "application.namespace" . }}
  defaultVolumesToRestic: {{  .Values.backup.defaultVolumesToRestic | default true }}
  snapshotVolumes: {{ .Values.backup.snapshotVolumes | default true }}
  storageLocation: {{ .Values.backup.storageLocation | quote }}
  ttl: {{ .Values.backup.ttl | default "1h0m0s" }}
{{- if .Values.backup.includedResources }}
  includedResources:
{{ toYaml .Values.backup.includedResources | indent 4 }}
{{- end -}}
{{- if .Values.backup.excludedResources }}
  excludedResources:
{{ toYaml .Values.backup.excludedResources | indent 4 }}
{{- end -}}
{{- end }}
