{{- if (.Values.backup).enabled }}
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: {{ printf "%s-backup" .Values.applicationName | trunc 63 | quote }}
  namespace: {{ .Values.backup.namespace | default ( include "application.namespace" . ) | quote }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- if .Values.backup.additionalLabels }}
    {{- toYaml .Values.backup.additionalLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.backup.annotations }}
  annotations:
    {{- toYaml .Values.backup.annotations | nindent 4 }}
  {{- end }}
spec:
  labelSelector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  {{- if not (kindIs "invalid" .Values.backup.includedNamespaces) }}
  includedNamespaces:
    {{- range $namespace := .Values.backup.includedNamespaces }}
    - {{ include "application.tplvalues.render" ( dict "value" $namespace "context" $ ) }}
    {{- end }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.defaultVolumesToRestic) }}
  defaultVolumesToRestic: {{ .Values.backup.defaultVolumesToRestic }}
  {{- else if not (kindIs "invalid" .Values.backup.defaultVolumesToFsBackup) }}
  defaultVolumesToFsBackup: {{ .Values.backup.defaultVolumesToFsBackup }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.snapshotVolumes) }}
  snapshotVolumes: {{ .Values.backup.snapshotVolumes }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.snapshotMoveData) }}
  snapshotMoveData: {{ .Values.backup.snapshotMoveData }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.csiSnapshotTimeout) }}
  csiSnapshotTimeout: {{ .Values.backup.csiSnapshotTimeout | quote }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.datamover) }}
  datamover: {{ .Values.backup.datamover | quote }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.itemOperationTimeout) }}
  itemOperationTimeout: {{ .Values.backup.itemOperationTimeout | quote }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.storageLocation) }}
  storageLocation: {{ .Values.backup.storageLocation | quote }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.ttl) }}
  ttl: {{ .Values.backup.ttl | quote }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.volumeSnapshotLocations) }}
  volumeSnapshotLocations:
    {{- toYaml .Values.backup.volumeSnapshotLocations | nindent 4 }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.includedResources) }}
  includedResources:
    {{- toYaml .Values.backup.includedResources | nindent 4 }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.excludedResources) }}
  excludedResources:
    {{- toYaml .Values.backup.excludedResources | nindent 4 }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.includedNamespaceScopedResources) }}
  includedNamespaceScopedResources:
    {{- toYaml .Values.backup.includedNamespaceScopedResources | nindent 4 }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.excludedNamespaceScopedResources) }}
  excludedNamespaceScopedResources:
    {{- toYaml .Values.backup.excludedNamespaceScopedResources | nindent 4 }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.backup.orderedResources) }}
  orderedResources:
    {{- toYaml .Values.backup.orderedResources | nindent 4 }}
  {{- end }}
{{- end }}
