{{- if (.Values.backup).enabled }}
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: {{ printf "%s-backup" .Values.applicationName | trunc 63 | quote }}
  namespace: {{ .Values.backup.namespace | default ( include "application.namespace" . ) | quote }}
  labels:
  {{- include "application.labels" $ | nindent 4 }}
{{- if .Values.backup.additionalLabels }}
{{ toYaml .Values.backup.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.backup.annotations }}
  annotations:
{{ toYaml .Values.backup.annotations | indent 4 }}
{{- end }}
spec:
  labelSelector:
    matchLabels:
{{ include "application.selectorLabels" . | indent 6 }}
  {{- range $namespace := .Values.backup.includedNamespaces }}
  includedNamespaces:
  - {{ include "application.tplvalues.render" ( dict "value" $namespace "context" $ ) }}
  {{- end }}
  defaultVolumesToFsBackup: {{  .Values.backup.defaultVolumesToFsBackup }}
  snapshotVolumes: {{ .Values.backup.snapshotVolumes }}
{{- if not (kindIs "invalid" .Values.backup.snapshotMoveData) }}
  snapshotMoveData: {{ .Values.backup.snapshotMoveData }}
{{- end }}
{{- if not (kindIs "invalid" .Values.backup.includeClusterResources) }}
  includeClusterResources: {{ .Values.backup.includeClusterResources }}
{{- end }}
{{- if .Values.backup.csiSnapshotTimeout }}
  csiSnapshotTimeout: {{ .Values.backup.csiSnapshotTimeout | quote }}
{{- end }}
{{- if .Values.backup.datamover }}
  datamover: {{ .Values.backup.datamover | quote }}
{{- end }}
{{- if .Values.backup.itemOperationTimeout }}
  itemOperationTimeout: {{ .Values.backup.itemOperationTimeout | quote }}
{{- end }}
  storageLocation: {{ .Values.backup.storageLocation | quote }}
  ttl: {{ .Values.backup.ttl }}
{{- if .Values.backup.volumeSnapshotLocations }}
  volumeSnapshotLocations:
{{ toYaml .Values.backup.volumeSnapshotLocations | indent 4 }}
{{- end }}
{{- if .Values.backup.includedResources }}
  includedResources:
{{ toYaml .Values.backup.includedResources | indent 4 }}
{{- end -}}
{{- if .Values.backup.excludedResources }}
  excludedResources:
{{ toYaml .Values.backup.excludedResources | indent 4 }}
{{- end -}}
{{- if .Values.backup.includedClusterScopedResources }}
  includedClusterScopedResources:
{{ toYaml .Values.backup.includedClusterScopedResources | indent 4 }}
{{- end -}}
{{- if .Values.backup.excludedClusterScopedResources }}
  excludedClusterScopedResources:
{{ toYaml .Values.backup.excludedClusterScopedResources | indent 4 }}
{{- end -}}
{{- if .Values.backup.includedNamespaceScopedResources }}
  includedNamespaceScopedResources:
{{ toYaml .Values.backup.includedNamespaceScopedResources | indent 4 }}
{{- end -}}
{{- if .Values.backup.excludedNamespaceScopedResources }}
  excludedNamespaceScopedResources:
{{ toYaml .Values.backup.excludedNamespaceScopedResources | indent 4 }}
{{- end -}}
{{- if .Values.backup.excludedNamespaces }}
  excludedNamespaces:
{{ toYaml .Values.backup.excludedNamespaces | indent 4 }}
{{- end -}}
{{- if .Values.backup.orderedResources }}
  orderedResources:
{{ toYaml .Values.backup.orderedResources | indent 4 }}
{{- end -}}
{{- end }}
