{{- if (.Values.backup).enabled }}
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: {{ printf "%s-backup" .Values.applicationName | trunc 63 | quote }}
  namespace: {{ .Values.backup.namespace | default ( include "application.namespace" . ) | quote }}
  labels:
  {{- include "application.labels" $ | nindent 4 }}
{{- if .Values.backup.additionalLabels }}
{{ toYaml .Values.backup.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.backup.annotations }}
  annotations:
{{ toYaml .Values.backup.annotations | indent 4 }}
{{- end }}
spec:
  labelSelector:
    matchLabels:
       app.kubernetes.io/part-of: {{ include "application.name" . }}
  {{- range $namespace := .Values.backup.includedNamespaces }}
  includedNamespaces:
  - {{ include "application.tplvalues.render" ( dict "value" $namespace "context" $ ) }}
  {{- end }}
  defaultVolumesToRestic: {{  .Values.backup.defaultVolumesToRestic }}
  snapshotVolumes: {{ .Values.backup.snapshotVolumes }}
  storageLocation: {{ .Values.backup.storageLocation | quote }}
  ttl: {{ .Values.backup.ttl }}
{{- if .Values.backup.includedResources }}
  includedResources:
{{ toYaml .Values.backup.includedResources | indent 4 }}
{{- end -}}
{{- if .Values.backup.excludedResources }}
  excludedResources:
{{ toYaml .Values.backup.excludedResources | indent 4 }}
{{- end -}}
{{- end }}
