{{- if and (.Values.rbac).enabled .Values.rbac.clusterRoles }}
{{- range .Values.rbac.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "application.name" $ }}-clusterrole-{{ .name }}
  labels:
  {{- include "application.labels" $ | nindent 4 }}
{{- if $.Values.rbac.additionalLabels }}
{{ toYaml $.Values.rbac.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.rbac.annotations }}
  annotations:
{{ toYaml $.Values.rbac.annotations | indent 4 }}
{{- end }}
rules:
{{ toYaml .rules | indent 2 }}
{{- end }}
{{- end }}
