{{- if .Values.externalSecret.enabled }}
{{- range .Values.externalSecret.files }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  {{- if eq .nameSuffix ""  }}
  name: {{ template "application.name" $ }}
  {{- else }}
  name: {{ template "application.name" $ }}-{{ .nameSuffix }}
  {{- end }}
spec:
  refreshInterval: {{ $.Values.externalSecret.refreshInterval }}
{{- if .data }}
  data:
{{- range $data := .data }}
    - secretKey: {{ $data.secretKey }}
      remoteRef: 
        key: {{ $data.remoteRef.key }}
        property: {{ $data.remoteRef.property }}
{{- end }}
  secretStoreRef:
    name: {{ .secretStoreRef.name }}
    kind: {{ .secretStoreRef.kind }}
  target:
    template:
      type: {{ .type }}
{{- if or .annotations .labels}}
      metadata:
{{- if .annotations }}
        annotations: 
{{ toYaml .annotations | indent 10 }}
{{- end }}
{{- if .labels }}
        labels: 
{{ toYaml .labels | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
{{- if .dataFrom }}
  dataFrom:
{{- range $data := .dataFrom }}
    - key: {{ $data.key }}
{{- end }}
  secretStoreRef:
    name: {{ .secretStoreRef.name }}
    kind: {{ .secretStoreRef.kind }}
  target:
    template:
      type: {{ .type }}
{{- if or .annotations .labels}}
      metadata:
{{- if .annotations }}
        annotations: 
{{ toYaml .annotations | indent 10 }}
{{- end }}
{{- if .labels }}
        labels: 
{{ toYaml .labels | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
---
{{- end}}
{{- end}}