{{- if .Values.externalSecret.enabled }}
{{- range .Values.externalSecret.files }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  {{- if .nameSuffix  }}
  {{- if eq .nameSuffix ""  }}
  name: {{ template "application.name" $ }}
  {{- else }}
  name: {{ template "application.name" $ }}-{{ .nameSuffix }}
  {{- end }}
  {{- else }}
  name: {{ template "application.name" $}}
  {{- end}}
spec:
  refreshInterval: {{ $.Values.externalSecret.refreshInterval }}
{{- if .data }}
  data:
{{ toYaml .data | indent 2  }}
{{- end }}
{{- if .dataFrom }}
  dataFrom:
{{ toYaml .dataFrom | indent 2  }}
{{- end }}
  {{- if .secretStore }}
  secretStoreRef:
    name: {{ .secretStore.name }}
    kind: {{ .secretStore.kind | default "SecretStore" }}
  {{- else }}
    secretStoreRef:
      name: {{ $.Values.externalSecret.secretStore.name }}
      kind: {{ $.Values.externalSecret.secretStore.kind | default "SecretStore" }}
  {{- end}}
  target:
    template:
      type: {{ .type | default "Opaque" }}
{{- if or .annotations .labels}}
      metadata:
{{- if .annotations }}
        annotations: 
{{ toYaml .annotations | indent 10 }}
{{- end }}
{{- if .labels }}
        labels: 
{{ toYaml .labels | indent 10 }}
{{- end }}
{{- end }}
---
{{- end}}
{{- end}}