{{- if .Values.forecastle }}
{{- if and (or .Values.ingress.enabled .Values.route.enabled) .Values.forecastle.enabled }}
apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  labels:
{{ include "application.labels.stakater" . | indent 4 }}
{{- if .Values.forecastle.additionalLabels }}
{{ toYaml .Values.forecastle.additionalLabels | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}
  namespace: {{ template "application.namespace" . }}
spec:
  name: {{ .Values.forecastle.displayName }}
  group: {{ default .Release.Namespace .Values.forecastle.group }}
  icon: {{ .Values.forecastle.icon }}
  urlFrom:
  {{- if .Values.ingress.enabled }}
    ingressRef:
      name: {{ template "application.name" . }}
  {{- else }}
    routeRef:
      name: {{ template "application.name" . }}
  {{- end }}
  networkRestricted: {{ .Values.forecastle.networkRestricted }}
  {{- if .Values.forecastle.properties }}
  properties:
{{ toYaml .Values.forecastle.properties | indent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}