{{- if (.Values.networkPolicy).enabled }}
---
apiVersion: "networking.k8s.io/v1"
kind: NetworkPolicy
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ include "application.namespace" . }}
  labels:
  {{- include "application.labels" . | nindent 4 }}
{{- if .Values.networkPolicy.additionalLabels }}
{{ toYaml .Values.networkPolicy.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.networkPolicy.annotations }}
  annotations:
{{ toYaml .Values.networkPolicy.annotations | indent 4 }}
{{- end }}
spec:
  podSelector:
    matchLabels:
{{ include "application.selectorLabels" . | indent 6 }}
{{- if .Values.deployment.podLabels }}
{{ toYaml .Values.deployment.podLabels | indent 6 }}
{{- end }}
{{- if or .Values.networkPolicy.ingress .Values.networkPolicy.egress }}
  policyTypes:
{{- if .Values.networkPolicy.ingress }}
    - Ingress
{{- end }}
{{- if .Values.networkPolicy.egress }}
    - Egress
{{- end }}
{{- end }}
{{- if .Values.networkPolicy.egress }}
  egress:
{{ toYaml .Values.networkPolicy.egress | indent 4 }}
{{- end }}
{{- if .Values.networkPolicy.ingress }}
  ingress:
{{ toYaml .Values.networkPolicy.ingress | indent 4 }}
{{- end }}
{{- end }}
