{{- if .Values.persistence }}
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
{{ include "application.labels.stakater" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.persistence.additionalLabels }}
{{ toYaml .Values.persistence.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
{{- if .Values.persistence.name }}
  name: "{{ .Values.persistence.name }}"
{{- else }}
  name: {{ template "application.name" . }}-data
{{- end }}
  namespace: {{ template "application.namespace" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- if .Values.persistence.volumeMode }}  
  volumeMode: "{{ .Values.persistence.volumeMode }}"
{{- end }}
{{- if .Values.persistence.volumeName }}  
  volumeName: "{{ .Values.persistence.volumeName }}"
{{- end }}
{{- end }}
{{- end }}
