{{- if (.Values.secret).enabled }}
{{- range $nameSuffix, $data := .Values.secret.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "application.name" $ }}-{{ $nameSuffix }}
  namespace: {{ template "application.namespace" $ }}
  labels:
  {{- include "application.labels" $ | nindent 4 }}
{{- if $.Values.secret.additionalLabels }}
{{ toYaml $.Values.secret.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.secret.annotations }}
  annotations:
{{ toYaml $.Values.secret.annotations | indent 4 }}
{{- end }}
data:
{{- range $key, $value := $data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
