{{- if and .Values.secret .Values.secret.enabled }}
{{- range .Values.secret.files }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "application.labels.stakater" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if $.Values.secret.additionalLabels }}
{{ toYaml $.Values.secret.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.secret.annotations }}
  annotations:
{{ toYaml $.Values.secret.annotations | indent 4 }}
{{- end }}
  {{- if eq .nameSuffix ""  }}
  name: {{ template "application.name" . }}
  {{- else }}
  name: {{ template "application.name" . }}-{{ .nameSuffix }}
  {{- end }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---
{{- end }}
{{- end }}