{{- if .Values.secret }}
{{- if .Values.secret.enabled }}
{{- range $nameSuffix, $data := .Values.secret.files }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "application.labels.stakater" $ | indent 4 }}
{{- if $.Values.secret.additionalLabels }}
{{ toYaml $.Values.secret.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.secret.annotations }}
  annotations:
{{ toYaml $.Values.secret.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" $ }}-{{ $nameSuffix }}
  namespace: {{ template "application.namespace" $ }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}