{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{.Values.secretProviderClass.name}}
  namespace: {{.Values.secretProviderClass.namespace}}
spec:
  provider: {{.Values.secretProviderClass.provider}}
  parameters:
    vaultAddress: {{.Values.secretProviderClass.parameters.vaultAddress}}
    roleName: {{.Values.secretProviderClass.parameters.roleName}}
    objects: 
    {{- if .Values.secretProviderClass.parameters.objects }}
    {{ toYaml .Values.secretProviderClass.parameters.objects | indent 4 }}
    {{- end }}
  secretObjects:
  {{- if .Values.secretProviderClass.secretObjects }}
  {{- range $value := .Values.secretProviderClass.secretObjects }}
    - data: {{- toYaml $value.data | nindent 8 }}  
      secretName: {{$value.secretName}}
      type: {{$value.type}}
    {{- end }}
  {{- end }}
  {{- end }}
