{{- define "application.sa.oauth-redirectreference" }}
apiVersion: v1
kind: OAuthRedirectReference
reference:
  kind: Route
  name: {{ include "application.name" . }}
{{- end }}

{{- if and .Values.rbac.enabled .Values.rbac.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "application.labels.stakater" . | nindent 4 }}
    {{- include "application.labels.chart" . | nindent 4 }}
    {{- with .Values.rbac.serviceAccount.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}

  annotations:
    {{- with .Values.rbac.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}

    {{- if .Values.deployment.openshiftOAuthProxy.enabled }}
    serviceaccounts.openshift.io/oauth-redirectreference.primary:
      {{- $reference := include "application.sa.oauth-redirectreference" . | fromYaml }}
      {{- toRawJson $reference | quote | nindent 6 }}
    {{- end }}

  namespace: {{ template "application.namespace" . }}

  name: {{ default (include "application.name" .) .Values.rbac.serviceAccount.name }}
{{- end }}
