{{- if and .Values.rbac.enabled .Values.rbac.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "application.labels.stakater" . | indent 4 }}
{{- if .Values.rbac.serviceAccount.additionalLabels }}
{{ toYaml .Values.rbac.serviceAccount.additionalLabels | indent 4 }}
{{- end }}
{{- if or .Values.rbac.serviceAccount.annotations .Values.deployment.openshiftOAuthProxy.enabled }}
  annotations:
  {{- if .Values.rbac.serviceAccount.annotations }}
{{ toYaml .Values.rbac.serviceAccount.annotations | indent 4 }}
  {{- end }}
  {{- if .Values.deployment.openshiftOAuthProxy.enabled }}
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ template "application.name" . }}"}}'
  {{- end }}
{{- end }}
  namespace: {{ template "application.namespace" . }}
{{- if .Values.rbac.serviceAccount.name }}
  name: {{ .Values.rbac.serviceAccount.name }}
{{- else }}
  name: {{ template "application.name" . }}
{{- end }}
{{- end }}
